### ISSUE TITLE
Add (very basic) IIIF support

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/newspaper-jp2-viewer#11]
Probably very hard-coded URI patterns, but long-term it sounds like chronam might be looking for IIIF URIs in order to make it easier to use external image servers.  I'd say we'd only need to support two URI patterns still, since this service is very specific to newspapers (and JP2 is very slow to manipulate in complex ways)

**Comment by kestlund** [comment]
See Mirador shim for ChronAm data: http://showcase.iiif.io/viewer/mirador2/chroniclingamerica.html

**Comment by jechols** [comment]
@kestlund, is there something that describes what you're talking about?  I just see a viewer page, so I'm not really sure what you're suggesting I look at.  Is there code or a spec or something beyond the standard IIIF spec?

**Comment by jechols** [comment]
http://iiif.io/api/image/2.0/compliance.html

I *think* we could be level-1-compliant just by implementing the URL patterns, proper status codes, JSON return, and a few of the http features.

**Comment by jechols** [comment]
Hmm, though it's worth noting we want to support the "native" quality to be more backward-compatible with IIIF 1.1.  Open Seadragon only mentions 1.1, so that would be a must for now.  There may be other compatibility issues to sort through as well.

**Comment by jechols** [comment]
DONE!
